# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: https://m1sti4ork7u8y.github.io/
title: Siou-Ci Programming Story
email: packtumi9722@gmail.com
author: Siou-Ci Syu
description: > # "Write an awesome description for your new site here. 
  Hello, welcome to my github.io.
copyright: 'Copyright &copy; 2018 Siou-Ci Syu. All Rights Reserved.'
credits: 'Credits: Landing Page is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com/">Start Bootstrap</a>.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: github
    url: https://github.com/M1stI4orK7U8y
  - title: linkedin
    url: https://www.linkedin.com/in/siouci-syu-info/
